CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
PROJECT(parking_local_mapping)

SET(CMAKE_CXX_STANDARD 17)
IF(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type" FORCE)
endif()


SET(ENABLE_OPENGL 1)


IF(ENABLE_OPENGL)
  MESSAGE("USING PANGOLIN AS VISUALIZATION")
  ADD_DEFINITIONS(-DENABLE_OPENGL)
  FIND_PACKAGE(Pangolin REQUIRED)
  INCLUDE_DIRECTORIES(${Pangolin_INCLUDE_DIRS})
ELSE()
  MESSAGE("NOT USING VIEWER")
ENDIF()

FIND_PACKAGE(Eigen3 REQUIRED)
INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIRS} ${EIGEN3_INCLUDE_DIRS}/unsupported)


INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/include)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/patac_protocol/include/protocol)

FIND_PACKAGE(OpenCV REQUIRED)
INCLUDE_DIRECTORIES(${OpenCV_INCLUDE_DIRS})


FIND_PACKAGE(Protobuf REQUIRED)
MESSAGE(STATUS "Using protobuf ${Protobuf_VERSION}")
INCLUDE_DIRECTORIES(${Protobuf_INCLUDE_DIRS})

MESSAGE("PRINTING ALL INCLUDE DIRS")
GET_PROPERTY(INCLUDE_DIRS DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY INCLUDE_DIRECTORIES)
FOREACH(DIR ${INCLUDE_DIRS})
  MESSAGE(STATUS "include_dir='${DIR}'")
ENDFOREACH()

MESSAGE("PRINTING ALL LINK_DIRECTORIES")
GET_PROPERTY(LINK_DIRECTORIES DIRECTORY PROPERTY LINK_DIRECTORIES)
FOREACH(DIR ${LINK_DIRECTORIES})
  MESSAGE(STATUS "link_dir='${DIR}'")
ENDFOREACH()

# add_library(sqlite3 STATIC ./src/sqlite3.c)
# target_link_libraries(sqlite3 Threads::Threads)
# target_include_directories(sqlite3 PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
# set_target_properties(sqlite3 PROPERTIES POSITION_INDEPENDENT_CODE ON)

FILE(GLOB SRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cc)
FILE(GLOB PROTO_FILES ${CMAKE_CURRENT_SOURCE_DIR}/patac_protocol/src/protocol/*.cc)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/patac_protocol/include/protocol/*.h)
MESSAGE(${SRC_FILES})

SET(FMT_USE_STATIC_LIBS ON)
FIND_PACKAGE(fmt REQUIRED)

ADD_LIBRARY(${PROJECT_NAME} SHARED ${SRC_FILES} ${PROTO_FILES})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} fmt::fmt   ${Protobuf_LIBRARIES} 
  ${OpenCV_LIBS} sqlite3)
IF(ENABLE_OPENGL)
  ADD_LIBRARY(viewer SHARED ${CMAKE_CURRENT_SOURCE_DIR}/src/visualization/pangolin_viewer.cc
                            ${CMAKE_CURRENT_SOURCE_DIR}/src/visualization/pangolin_drawer.cc
                            
                            )
  TARGET_LINK_LIBRARIES(viewer ${Pangolin_LIBRARIES} ${PROJECT_NAME} )
ENDIF()

# ADD_EXECUTABLE(run_sim ${CMAKE_CURRENT_SOURCE_DIR}/exe/sim_main.cc)
# TARGET_LINK_LIBRARIES(run_sim ${PROJECT_NAME})
# IF(ENABLE_OPENGL)
#   TARGET_LINK_LIBRARIES(run_sim viewer ${Pangolin_LIBRARIES})
# ENDIF()

ADD_EXECUTABLE(run_fillback ${CMAKE_CURRENT_SOURCE_DIR}/exe/fillback_main.cc)
TARGET_LINK_LIBRARIES(run_fillback ${PROJECT_NAME})
IF(ENABLE_OPENGL)
  TARGET_LINK_LIBRARIES(run_fillback viewer ${Pangolin_LIBRARIES})
ENDIF()

ADD_EXECUTABLE(run_interface ${CMAKE_CURRENT_SOURCE_DIR}/exe/interface_main.cc)
TARGET_LINK_LIBRARIES(run_interface ${PROJECT_NAME})
IF(ENABLE_OPENGL)
  TARGET_LINK_LIBRARIES(run_interface viewer ${Pangolin_LIBRARIES})
ENDIF()
# 
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/unit_test)






