// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hmi_render.proto

#include "hmi_render.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace autodrive {
namespace workflow {
namespace proto {
class FusionParkingSlotsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FusionParkingSlots>
      _instance;
} _FusionParkingSlots_default_instance_;
class HmiRenderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<HmiRender>
      _instance;
} _HmiRender_default_instance_;
class HmiRenderMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<HmiRenderMsg>
      _instance;
} _HmiRenderMsg_default_instance_;
}  // namespace proto
}  // namespace workflow
}  // namespace autodrive
namespace protobuf_hmi_5frender_2eproto {
void InitDefaultsFusionParkingSlotsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_parking_5fslot_2eproto::InitDefaultsParkingSlotInfo();
  {
    void* ptr = &::autodrive::workflow::proto::_FusionParkingSlots_default_instance_;
    new (ptr) ::autodrive::workflow::proto::FusionParkingSlots();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::autodrive::workflow::proto::FusionParkingSlots::InitAsDefaultInstance();
}

void InitDefaultsFusionParkingSlots() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFusionParkingSlotsImpl);
}

void InitDefaultsHmiRenderImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_fusion_5fobstacle_2eproto::InitDefaultsFusionObstacles();
  protobuf_hmi_5frender_2eproto::InitDefaultsFusionParkingSlots();
  {
    void* ptr = &::autodrive::workflow::proto::_HmiRender_default_instance_;
    new (ptr) ::autodrive::workflow::proto::HmiRender();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::autodrive::workflow::proto::HmiRender::InitAsDefaultInstance();
}

void InitDefaultsHmiRender() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHmiRenderImpl);
}

void InitDefaultsHmiRenderMsgImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_common_2eproto::InitDefaultsMsgHeader();
  protobuf_common_2eproto::InitDefaultsError();
  protobuf_hmi_5frender_2eproto::InitDefaultsHmiRender();
  {
    void* ptr = &::autodrive::workflow::proto::_HmiRenderMsg_default_instance_;
    new (ptr) ::autodrive::workflow::proto::HmiRenderMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::autodrive::workflow::proto::HmiRenderMsg::InitAsDefaultInstance();
}

void InitDefaultsHmiRenderMsg() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHmiRenderMsgImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::FusionParkingSlots, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::FusionParkingSlots, parking_slots_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::FusionParkingSlots, certified_slots_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRender, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRender, obstacles_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRender, parking_slots_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRenderMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRenderMsg, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRenderMsg, error_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::autodrive::workflow::proto::HmiRenderMsg, hmi_render_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::autodrive::workflow::proto::FusionParkingSlots)},
  { 7, -1, sizeof(::autodrive::workflow::proto::HmiRender)},
  { 14, -1, sizeof(::autodrive::workflow::proto::HmiRenderMsg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::autodrive::workflow::proto::_FusionParkingSlots_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::autodrive::workflow::proto::_HmiRender_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::autodrive::workflow::proto::_HmiRenderMsg_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "hmi_render.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020hmi_render.proto\022\030autodrive.workflow.p"
      "roto\032\014common.proto\032\025fusion_obstacle.prot"
      "o\032\022parking_slot.proto\"|\n\022FusionParkingSl"
      "ots\022M\n\rparking_slots\030\001 \003(\01326.autodrive.w"
      "orkflow.proto.parking_slot.ParkingSlotIn"
      "fo\022\027\n\017certified_slots\030\002 \003(\005\"\216\001\n\tHmiRende"
      "r\022<\n\tobstacles\030\001 \001(\0132).autodrive.workflo"
      "w.proto.FusionObstacles\022C\n\rparking_slots"
      "\030\002 \001(\0132,.autodrive.workflow.proto.Fusion"
      "ParkingSlots\"\254\001\n\014HmiRenderMsg\0223\n\006header\030"
      "\001 \001(\0132#.autodrive.workflow.proto.MsgHead"
      "er\022.\n\005error\030\002 \001(\0132\037.autodrive.workflow.p"
      "roto.Error\0227\n\nhmi_render\030\003 \001(\0132#.autodri"
      "ve.workflow.proto.HmiRenderb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 555);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hmi_render.proto", &protobuf_RegisterTypes);
  ::protobuf_common_2eproto::AddDescriptors();
  ::protobuf_fusion_5fobstacle_2eproto::AddDescriptors();
  ::protobuf_parking_5fslot_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_hmi_5frender_2eproto
namespace autodrive {
namespace workflow {
namespace proto {

// ===================================================================

void FusionParkingSlots::InitAsDefaultInstance() {
}
void FusionParkingSlots::clear_parking_slots() {
  parking_slots_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FusionParkingSlots::kParkingSlotsFieldNumber;
const int FusionParkingSlots::kCertifiedSlotsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FusionParkingSlots::FusionParkingSlots()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_hmi_5frender_2eproto::InitDefaultsFusionParkingSlots();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:autodrive.workflow.proto.FusionParkingSlots)
}
FusionParkingSlots::FusionParkingSlots(const FusionParkingSlots& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      parking_slots_(from.parking_slots_),
      certified_slots_(from.certified_slots_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:autodrive.workflow.proto.FusionParkingSlots)
}

void FusionParkingSlots::SharedCtor() {
  _cached_size_ = 0;
}

FusionParkingSlots::~FusionParkingSlots() {
  // @@protoc_insertion_point(destructor:autodrive.workflow.proto.FusionParkingSlots)
  SharedDtor();
}

void FusionParkingSlots::SharedDtor() {
}

void FusionParkingSlots::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FusionParkingSlots::descriptor() {
  ::protobuf_hmi_5frender_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hmi_5frender_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FusionParkingSlots& FusionParkingSlots::default_instance() {
  ::protobuf_hmi_5frender_2eproto::InitDefaultsFusionParkingSlots();
  return *internal_default_instance();
}

FusionParkingSlots* FusionParkingSlots::New(::google::protobuf::Arena* arena) const {
  FusionParkingSlots* n = new FusionParkingSlots;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FusionParkingSlots::Clear() {
// @@protoc_insertion_point(message_clear_start:autodrive.workflow.proto.FusionParkingSlots)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  parking_slots_.Clear();
  certified_slots_.Clear();
  _internal_metadata_.Clear();
}

bool FusionParkingSlots::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:autodrive.workflow.proto.FusionParkingSlots)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .autodrive.workflow.proto.parking_slot.ParkingSlotInfo parking_slots = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_parking_slots()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 certified_slots = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_certified_slots())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_certified_slots())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:autodrive.workflow.proto.FusionParkingSlots)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:autodrive.workflow.proto.FusionParkingSlots)
  return false;
#undef DO_
}

void FusionParkingSlots::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:autodrive.workflow.proto.FusionParkingSlots)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .autodrive.workflow.proto.parking_slot.ParkingSlotInfo parking_slots = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->parking_slots_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->parking_slots(static_cast<int>(i)), output);
  }

  // repeated int32 certified_slots = 2;
  if (this->certified_slots_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _certified_slots_cached_byte_size_));
  }
  for (int i = 0, n = this->certified_slots_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->certified_slots(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:autodrive.workflow.proto.FusionParkingSlots)
}

::google::protobuf::uint8* FusionParkingSlots::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:autodrive.workflow.proto.FusionParkingSlots)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .autodrive.workflow.proto.parking_slot.ParkingSlotInfo parking_slots = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->parking_slots_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->parking_slots(static_cast<int>(i)), deterministic, target);
  }

  // repeated int32 certified_slots = 2;
  if (this->certified_slots_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _certified_slots_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->certified_slots_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:autodrive.workflow.proto.FusionParkingSlots)
  return target;
}

size_t FusionParkingSlots::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:autodrive.workflow.proto.FusionParkingSlots)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .autodrive.workflow.proto.parking_slot.ParkingSlotInfo parking_slots = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->parking_slots_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->parking_slots(static_cast<int>(i)));
    }
  }

  // repeated int32 certified_slots = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->certified_slots_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _certified_slots_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FusionParkingSlots::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:autodrive.workflow.proto.FusionParkingSlots)
  GOOGLE_DCHECK_NE(&from, this);
  const FusionParkingSlots* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FusionParkingSlots>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:autodrive.workflow.proto.FusionParkingSlots)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:autodrive.workflow.proto.FusionParkingSlots)
    MergeFrom(*source);
  }
}

void FusionParkingSlots::MergeFrom(const FusionParkingSlots& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:autodrive.workflow.proto.FusionParkingSlots)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  parking_slots_.MergeFrom(from.parking_slots_);
  certified_slots_.MergeFrom(from.certified_slots_);
}

void FusionParkingSlots::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:autodrive.workflow.proto.FusionParkingSlots)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FusionParkingSlots::CopyFrom(const FusionParkingSlots& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:autodrive.workflow.proto.FusionParkingSlots)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FusionParkingSlots::IsInitialized() const {
  return true;
}

void FusionParkingSlots::Swap(FusionParkingSlots* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FusionParkingSlots::InternalSwap(FusionParkingSlots* other) {
  using std::swap;
  parking_slots_.InternalSwap(&other->parking_slots_);
  certified_slots_.InternalSwap(&other->certified_slots_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FusionParkingSlots::GetMetadata() const {
  protobuf_hmi_5frender_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hmi_5frender_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void HmiRender::InitAsDefaultInstance() {
  ::autodrive::workflow::proto::_HmiRender_default_instance_._instance.get_mutable()->obstacles_ = const_cast< ::autodrive::workflow::proto::FusionObstacles*>(
      ::autodrive::workflow::proto::FusionObstacles::internal_default_instance());
  ::autodrive::workflow::proto::_HmiRender_default_instance_._instance.get_mutable()->parking_slots_ = const_cast< ::autodrive::workflow::proto::FusionParkingSlots*>(
      ::autodrive::workflow::proto::FusionParkingSlots::internal_default_instance());
}
void HmiRender::clear_obstacles() {
  if (GetArenaNoVirtual() == NULL && obstacles_ != NULL) {
    delete obstacles_;
  }
  obstacles_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HmiRender::kObstaclesFieldNumber;
const int HmiRender::kParkingSlotsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HmiRender::HmiRender()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_hmi_5frender_2eproto::InitDefaultsHmiRender();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:autodrive.workflow.proto.HmiRender)
}
HmiRender::HmiRender(const HmiRender& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_obstacles()) {
    obstacles_ = new ::autodrive::workflow::proto::FusionObstacles(*from.obstacles_);
  } else {
    obstacles_ = NULL;
  }
  if (from.has_parking_slots()) {
    parking_slots_ = new ::autodrive::workflow::proto::FusionParkingSlots(*from.parking_slots_);
  } else {
    parking_slots_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:autodrive.workflow.proto.HmiRender)
}

void HmiRender::SharedCtor() {
  ::memset(&obstacles_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&parking_slots_) -
      reinterpret_cast<char*>(&obstacles_)) + sizeof(parking_slots_));
  _cached_size_ = 0;
}

HmiRender::~HmiRender() {
  // @@protoc_insertion_point(destructor:autodrive.workflow.proto.HmiRender)
  SharedDtor();
}

void HmiRender::SharedDtor() {
  if (this != internal_default_instance()) delete obstacles_;
  if (this != internal_default_instance()) delete parking_slots_;
}

void HmiRender::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HmiRender::descriptor() {
  ::protobuf_hmi_5frender_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hmi_5frender_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HmiRender& HmiRender::default_instance() {
  ::protobuf_hmi_5frender_2eproto::InitDefaultsHmiRender();
  return *internal_default_instance();
}

HmiRender* HmiRender::New(::google::protobuf::Arena* arena) const {
  HmiRender* n = new HmiRender;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HmiRender::Clear() {
// @@protoc_insertion_point(message_clear_start:autodrive.workflow.proto.HmiRender)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && obstacles_ != NULL) {
    delete obstacles_;
  }
  obstacles_ = NULL;
  if (GetArenaNoVirtual() == NULL && parking_slots_ != NULL) {
    delete parking_slots_;
  }
  parking_slots_ = NULL;
  _internal_metadata_.Clear();
}

bool HmiRender::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:autodrive.workflow.proto.HmiRender)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .autodrive.workflow.proto.FusionObstacles obstacles = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_obstacles()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .autodrive.workflow.proto.FusionParkingSlots parking_slots = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_parking_slots()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:autodrive.workflow.proto.HmiRender)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:autodrive.workflow.proto.HmiRender)
  return false;
#undef DO_
}

void HmiRender::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:autodrive.workflow.proto.HmiRender)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .autodrive.workflow.proto.FusionObstacles obstacles = 1;
  if (this->has_obstacles()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->obstacles_, output);
  }

  // .autodrive.workflow.proto.FusionParkingSlots parking_slots = 2;
  if (this->has_parking_slots()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->parking_slots_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:autodrive.workflow.proto.HmiRender)
}

::google::protobuf::uint8* HmiRender::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:autodrive.workflow.proto.HmiRender)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .autodrive.workflow.proto.FusionObstacles obstacles = 1;
  if (this->has_obstacles()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->obstacles_, deterministic, target);
  }

  // .autodrive.workflow.proto.FusionParkingSlots parking_slots = 2;
  if (this->has_parking_slots()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->parking_slots_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:autodrive.workflow.proto.HmiRender)
  return target;
}

size_t HmiRender::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:autodrive.workflow.proto.HmiRender)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .autodrive.workflow.proto.FusionObstacles obstacles = 1;
  if (this->has_obstacles()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->obstacles_);
  }

  // .autodrive.workflow.proto.FusionParkingSlots parking_slots = 2;
  if (this->has_parking_slots()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->parking_slots_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HmiRender::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:autodrive.workflow.proto.HmiRender)
  GOOGLE_DCHECK_NE(&from, this);
  const HmiRender* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HmiRender>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:autodrive.workflow.proto.HmiRender)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:autodrive.workflow.proto.HmiRender)
    MergeFrom(*source);
  }
}

void HmiRender::MergeFrom(const HmiRender& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:autodrive.workflow.proto.HmiRender)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_obstacles()) {
    mutable_obstacles()->::autodrive::workflow::proto::FusionObstacles::MergeFrom(from.obstacles());
  }
  if (from.has_parking_slots()) {
    mutable_parking_slots()->::autodrive::workflow::proto::FusionParkingSlots::MergeFrom(from.parking_slots());
  }
}

void HmiRender::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:autodrive.workflow.proto.HmiRender)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HmiRender::CopyFrom(const HmiRender& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:autodrive.workflow.proto.HmiRender)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HmiRender::IsInitialized() const {
  return true;
}

void HmiRender::Swap(HmiRender* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HmiRender::InternalSwap(HmiRender* other) {
  using std::swap;
  swap(obstacles_, other->obstacles_);
  swap(parking_slots_, other->parking_slots_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HmiRender::GetMetadata() const {
  protobuf_hmi_5frender_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hmi_5frender_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void HmiRenderMsg::InitAsDefaultInstance() {
  ::autodrive::workflow::proto::_HmiRenderMsg_default_instance_._instance.get_mutable()->header_ = const_cast< ::autodrive::workflow::proto::MsgHeader*>(
      ::autodrive::workflow::proto::MsgHeader::internal_default_instance());
  ::autodrive::workflow::proto::_HmiRenderMsg_default_instance_._instance.get_mutable()->error_ = const_cast< ::autodrive::workflow::proto::Error*>(
      ::autodrive::workflow::proto::Error::internal_default_instance());
  ::autodrive::workflow::proto::_HmiRenderMsg_default_instance_._instance.get_mutable()->hmi_render_ = const_cast< ::autodrive::workflow::proto::HmiRender*>(
      ::autodrive::workflow::proto::HmiRender::internal_default_instance());
}
void HmiRenderMsg::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
}
void HmiRenderMsg::clear_error() {
  if (GetArenaNoVirtual() == NULL && error_ != NULL) {
    delete error_;
  }
  error_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HmiRenderMsg::kHeaderFieldNumber;
const int HmiRenderMsg::kErrorFieldNumber;
const int HmiRenderMsg::kHmiRenderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HmiRenderMsg::HmiRenderMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_hmi_5frender_2eproto::InitDefaultsHmiRenderMsg();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:autodrive.workflow.proto.HmiRenderMsg)
}
HmiRenderMsg::HmiRenderMsg(const HmiRenderMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::autodrive::workflow::proto::MsgHeader(*from.header_);
  } else {
    header_ = NULL;
  }
  if (from.has_error()) {
    error_ = new ::autodrive::workflow::proto::Error(*from.error_);
  } else {
    error_ = NULL;
  }
  if (from.has_hmi_render()) {
    hmi_render_ = new ::autodrive::workflow::proto::HmiRender(*from.hmi_render_);
  } else {
    hmi_render_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:autodrive.workflow.proto.HmiRenderMsg)
}

void HmiRenderMsg::SharedCtor() {
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hmi_render_) -
      reinterpret_cast<char*>(&header_)) + sizeof(hmi_render_));
  _cached_size_ = 0;
}

HmiRenderMsg::~HmiRenderMsg() {
  // @@protoc_insertion_point(destructor:autodrive.workflow.proto.HmiRenderMsg)
  SharedDtor();
}

void HmiRenderMsg::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete error_;
  if (this != internal_default_instance()) delete hmi_render_;
}

void HmiRenderMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HmiRenderMsg::descriptor() {
  ::protobuf_hmi_5frender_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hmi_5frender_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HmiRenderMsg& HmiRenderMsg::default_instance() {
  ::protobuf_hmi_5frender_2eproto::InitDefaultsHmiRenderMsg();
  return *internal_default_instance();
}

HmiRenderMsg* HmiRenderMsg::New(::google::protobuf::Arena* arena) const {
  HmiRenderMsg* n = new HmiRenderMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HmiRenderMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:autodrive.workflow.proto.HmiRenderMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  if (GetArenaNoVirtual() == NULL && error_ != NULL) {
    delete error_;
  }
  error_ = NULL;
  if (GetArenaNoVirtual() == NULL && hmi_render_ != NULL) {
    delete hmi_render_;
  }
  hmi_render_ = NULL;
  _internal_metadata_.Clear();
}

bool HmiRenderMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:autodrive.workflow.proto.HmiRenderMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .autodrive.workflow.proto.MsgHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .autodrive.workflow.proto.Error error = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_error()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .autodrive.workflow.proto.HmiRender hmi_render = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_hmi_render()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:autodrive.workflow.proto.HmiRenderMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:autodrive.workflow.proto.HmiRenderMsg)
  return false;
#undef DO_
}

void HmiRenderMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:autodrive.workflow.proto.HmiRenderMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .autodrive.workflow.proto.MsgHeader header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->header_, output);
  }

  // .autodrive.workflow.proto.Error error = 2;
  if (this->has_error()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->error_, output);
  }

  // .autodrive.workflow.proto.HmiRender hmi_render = 3;
  if (this->has_hmi_render()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->hmi_render_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:autodrive.workflow.proto.HmiRenderMsg)
}

::google::protobuf::uint8* HmiRenderMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:autodrive.workflow.proto.HmiRenderMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .autodrive.workflow.proto.MsgHeader header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->header_, deterministic, target);
  }

  // .autodrive.workflow.proto.Error error = 2;
  if (this->has_error()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->error_, deterministic, target);
  }

  // .autodrive.workflow.proto.HmiRender hmi_render = 3;
  if (this->has_hmi_render()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->hmi_render_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:autodrive.workflow.proto.HmiRenderMsg)
  return target;
}

size_t HmiRenderMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:autodrive.workflow.proto.HmiRenderMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .autodrive.workflow.proto.MsgHeader header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->header_);
  }

  // .autodrive.workflow.proto.Error error = 2;
  if (this->has_error()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->error_);
  }

  // .autodrive.workflow.proto.HmiRender hmi_render = 3;
  if (this->has_hmi_render()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->hmi_render_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HmiRenderMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:autodrive.workflow.proto.HmiRenderMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const HmiRenderMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HmiRenderMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:autodrive.workflow.proto.HmiRenderMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:autodrive.workflow.proto.HmiRenderMsg)
    MergeFrom(*source);
  }
}

void HmiRenderMsg::MergeFrom(const HmiRenderMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:autodrive.workflow.proto.HmiRenderMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_header()) {
    mutable_header()->::autodrive::workflow::proto::MsgHeader::MergeFrom(from.header());
  }
  if (from.has_error()) {
    mutable_error()->::autodrive::workflow::proto::Error::MergeFrom(from.error());
  }
  if (from.has_hmi_render()) {
    mutable_hmi_render()->::autodrive::workflow::proto::HmiRender::MergeFrom(from.hmi_render());
  }
}

void HmiRenderMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:autodrive.workflow.proto.HmiRenderMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HmiRenderMsg::CopyFrom(const HmiRenderMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:autodrive.workflow.proto.HmiRenderMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HmiRenderMsg::IsInitialized() const {
  return true;
}

void HmiRenderMsg::Swap(HmiRenderMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HmiRenderMsg::InternalSwap(HmiRenderMsg* other) {
  using std::swap;
  swap(header_, other->header_);
  swap(error_, other->error_);
  swap(hmi_render_, other->hmi_render_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HmiRenderMsg::GetMetadata() const {
  protobuf_hmi_5frender_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_hmi_5frender_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace workflow
}  // namespace autodrive

// @@protoc_insertion_point(global_scope)
