# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_extrinsics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_extrinsics.proto',
  package='autodrive.workflow.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x63\x61mera_extrinsics.proto\x12\x18\x61utodrive.workflow.proto\x1a\x0c\x63ommon.proto\"\xa1\x01\n\tExtrinsic\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0c\n\x04roll\x18\x04 \x01(\x02\x12\r\n\x05pitch\x18\x05 \x01(\x02\x12\x0b\n\x03yaw\x18\x06 \x01(\x02\x12\x32\n\x06\x63\x61m_id\x18\x07 \x01(\x0e\x32\".autodrive.workflow.proto.CameraID\x12\x15\n\rnum_extrinsic\x18\x08 \x01(\r\"\xb3\x01\n\x13\x43\x61meraExtrinsicsMsg\x12\x33\n\x06header\x18\x01 \x01(\x0b\x32#.autodrive.workflow.proto.MsgHeader\x12.\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1f.autodrive.workflow.proto.Error\x12\x37\n\nextrinsics\x18\x03 \x03(\x0b\x32#.autodrive.workflow.proto.Extrinsic*\xd7\x02\n\x08\x43\x61meraID\x12\x1c\n\x18\x43\x41MERA_DIRECTION_UNKNOWN\x10\x00\x12\x19\n\x15\x43\x41MERA_DIRECTION_BACK\x10\x01\x12\x1a\n\x16\x43\x41MERA_DIRECTION_FRONT\x10\x02\x12\x19\n\x15\x43\x41MERA_DIRECTION_LEFT\x10\x03\x12\x1a\n\x16\x43\x41MERA_DIRECTION_RIGHT\x10\x04\x12\x1d\n\x19\x43\x41MERA_DIRECTION_PIN_REAR\x10\x05\x12\x1e\n\x1a\x43\x41MERA_DIRECTION_PIN_FRONT\x10\x06\x12\x1e\n\x1a\x43\x41MERA_DIRECTION_OMNI_BACK\x10\x07\x12\x1f\n\x1b\x43\x41MERA_DIRECTION_OMNI_FRONT\x10\x08\x12\x1e\n\x1a\x43\x41MERA_DIRECTION_OMNI_LEFT\x10\t\x12\x1f\n\x1b\x43\x41MERA_DIRECTION_OMNI_RIGHT\x10\nb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_CAMERAID = _descriptor.EnumDescriptor(
  name='CameraID',
  full_name='autodrive.workflow.proto.CameraID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_BACK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_FRONT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_LEFT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_RIGHT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_PIN_REAR', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_PIN_FRONT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_OMNI_BACK', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_OMNI_FRONT', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_OMNI_LEFT', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAMERA_DIRECTION_OMNI_RIGHT', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=414,
  serialized_end=757,
)
_sym_db.RegisterEnumDescriptor(_CAMERAID)

CameraID = enum_type_wrapper.EnumTypeWrapper(_CAMERAID)
CAMERA_DIRECTION_UNKNOWN = 0
CAMERA_DIRECTION_BACK = 1
CAMERA_DIRECTION_FRONT = 2
CAMERA_DIRECTION_LEFT = 3
CAMERA_DIRECTION_RIGHT = 4
CAMERA_DIRECTION_PIN_REAR = 5
CAMERA_DIRECTION_PIN_FRONT = 6
CAMERA_DIRECTION_OMNI_BACK = 7
CAMERA_DIRECTION_OMNI_FRONT = 8
CAMERA_DIRECTION_OMNI_LEFT = 9
CAMERA_DIRECTION_OMNI_RIGHT = 10



_EXTRINSIC = _descriptor.Descriptor(
  name='Extrinsic',
  full_name='autodrive.workflow.proto.Extrinsic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='autodrive.workflow.proto.Extrinsic.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='autodrive.workflow.proto.Extrinsic.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='autodrive.workflow.proto.Extrinsic.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='autodrive.workflow.proto.Extrinsic.roll', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='autodrive.workflow.proto.Extrinsic.pitch', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='autodrive.workflow.proto.Extrinsic.yaw', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cam_id', full_name='autodrive.workflow.proto.Extrinsic.cam_id', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_extrinsic', full_name='autodrive.workflow.proto.Extrinsic.num_extrinsic', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=229,
)


_CAMERAEXTRINSICSMSG = _descriptor.Descriptor(
  name='CameraExtrinsicsMsg',
  full_name='autodrive.workflow.proto.CameraExtrinsicsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='autodrive.workflow.proto.CameraExtrinsicsMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='autodrive.workflow.proto.CameraExtrinsicsMsg.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extrinsics', full_name='autodrive.workflow.proto.CameraExtrinsicsMsg.extrinsics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=411,
)

_EXTRINSIC.fields_by_name['cam_id'].enum_type = _CAMERAID
_CAMERAEXTRINSICSMSG.fields_by_name['header'].message_type = common__pb2._MSGHEADER
_CAMERAEXTRINSICSMSG.fields_by_name['error'].message_type = common__pb2._ERROR
_CAMERAEXTRINSICSMSG.fields_by_name['extrinsics'].message_type = _EXTRINSIC
DESCRIPTOR.message_types_by_name['Extrinsic'] = _EXTRINSIC
DESCRIPTOR.message_types_by_name['CameraExtrinsicsMsg'] = _CAMERAEXTRINSICSMSG
DESCRIPTOR.enum_types_by_name['CameraID'] = _CAMERAID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Extrinsic = _reflection.GeneratedProtocolMessageType('Extrinsic', (_message.Message,), dict(
  DESCRIPTOR = _EXTRINSIC,
  __module__ = 'camera_extrinsics_pb2'
  # @@protoc_insertion_point(class_scope:autodrive.workflow.proto.Extrinsic)
  ))
_sym_db.RegisterMessage(Extrinsic)

CameraExtrinsicsMsg = _reflection.GeneratedProtocolMessageType('CameraExtrinsicsMsg', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAEXTRINSICSMSG,
  __module__ = 'camera_extrinsics_pb2'
  # @@protoc_insertion_point(class_scope:autodrive.workflow.proto.CameraExtrinsicsMsg)
  ))
_sym_db.RegisterMessage(CameraExtrinsicsMsg)


# @@protoc_insertion_point(module_scope)
