# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fusion_parking_slots.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import parking_slot_pb2 as parking__slot__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fusion_parking_slots.proto',
  package='autodrive.workflow.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x66usion_parking_slots.proto\x12\x18\x61utodrive.workflow.proto\x1a\x12parking_slot.proto\x1a\x0c\x63ommon.proto\"\xe4\x01\n\x15\x46usionParkingSlotsMsg\x12\x33\n\x06header\x18\x01 \x01(\x0b\x32#.autodrive.workflow.proto.MsgHeader\x12.\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1f.autodrive.workflow.proto.Error\x12M\n\rparking_slots\x18\x03 \x03(\x0b\x32\x36.autodrive.workflow.proto.parking_slot.ParkingSlotInfo\x12\x17\n\x0f\x63\x65rtified_slots\x18\x04 \x03(\x05\x62\x06proto3')
  ,
  dependencies=[parking__slot__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_FUSIONPARKINGSLOTSMSG = _descriptor.Descriptor(
  name='FusionParkingSlotsMsg',
  full_name='autodrive.workflow.proto.FusionParkingSlotsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='autodrive.workflow.proto.FusionParkingSlotsMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='autodrive.workflow.proto.FusionParkingSlotsMsg.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parking_slots', full_name='autodrive.workflow.proto.FusionParkingSlotsMsg.parking_slots', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='certified_slots', full_name='autodrive.workflow.proto.FusionParkingSlotsMsg.certified_slots', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=319,
)

_FUSIONPARKINGSLOTSMSG.fields_by_name['header'].message_type = common__pb2._MSGHEADER
_FUSIONPARKINGSLOTSMSG.fields_by_name['error'].message_type = common__pb2._ERROR
_FUSIONPARKINGSLOTSMSG.fields_by_name['parking_slots'].message_type = parking__slot__pb2._PARKINGSLOTINFO
DESCRIPTOR.message_types_by_name['FusionParkingSlotsMsg'] = _FUSIONPARKINGSLOTSMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FusionParkingSlotsMsg = _reflection.GeneratedProtocolMessageType('FusionParkingSlotsMsg', (_message.Message,), dict(
  DESCRIPTOR = _FUSIONPARKINGSLOTSMSG,
  __module__ = 'fusion_parking_slots_pb2'
  # @@protoc_insertion_point(class_scope:autodrive.workflow.proto.FusionParkingSlotsMsg)
  ))
_sym_db.RegisterMessage(FusionParkingSlotsMsg)


# @@protoc_insertion_point(module_scope)
