# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: real3d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dynamic_obstacle_pb2 as dynamic__obstacle__pb2
import perception_base_pb2 as perception__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='real3d.proto',
  package='autodrive.workflow.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0creal3d.proto\x12\x18\x61utodrive.workflow.proto\x1a\x16\x64ynamic_obstacle.proto\x1a\x15perception_base.proto\"\xd5\x01\n\x0cReal3DResult\x12?\n\x0c\x62\x65v_obstacle\x18\x01 \x01(\x0b\x32).autodrive.workflow.proto.DynamicObstacle\x12\x42\n\timg_3dbox\x18\x02 \x01(\x0b\x32/.autodrive.workflow.proto.perception_base.Box3D\x12@\n\x08img_rect\x18\x03 \x01(\x0b\x32..autodrive.workflow.proto.perception_base.Rect\"\xdd\x01\n\rReal3DResults\x12@\n\x06header\x18\x01 \x01(\x0b\x32\x30.autodrive.workflow.proto.perception_base.Header\x12\x32\n\x04type\x18\x02 \x01(\x0e\x32$.autodrive.workflow.proto.Real3DType\x12\x17\n\x0f\x63oordinate_type\x18\x03 \x01(\t\x12=\n\rreal3d_result\x18\x04 \x03(\x0b\x32&.autodrive.workflow.proto.Real3DResult\"\x8f\x01\n\nReal3DData\x12@\n\x06header\x18\x01 \x01(\x0b\x32\x30.autodrive.workflow.proto.perception_base.Header\x12?\n\x0ereal3d_results\x18\x02 \x03(\x0b\x32\'.autodrive.workflow.proto.Real3DResults*W\n\nReal3DType\x12\x19\n\x15kReal3DTypePedestrian\x10\x00\x12\x16\n\x12kReal3DTypeVehicle\x10\x01\x12\x16\n\x12kReal3DTypeCyclist\x10\x02*\x84\x01\n\x0cRoi3DMapType\x12\x1f\n\x1bkRoi3DMapTypePtUndistortMap\x10\x00\x12\x1d\n\x19kRoi3DMapTypePtDistortMap\x10\x01\x12\x19\n\x15kRoi3DMapTypeEqflUMap\x10\x02\x12\x19\n\x15kRoi3DMapTypeEqflVMap\x10\x03\x62\x06proto3')
  ,
  dependencies=[dynamic__obstacle__pb2.DESCRIPTOR,perception__base__pb2.DESCRIPTOR,])

_REAL3DTYPE = _descriptor.EnumDescriptor(
  name='Real3DType',
  full_name='autodrive.workflow.proto.Real3DType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kReal3DTypePedestrian', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kReal3DTypeVehicle', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kReal3DTypeCyclist', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=675,
  serialized_end=762,
)
_sym_db.RegisterEnumDescriptor(_REAL3DTYPE)

Real3DType = enum_type_wrapper.EnumTypeWrapper(_REAL3DTYPE)
_ROI3DMAPTYPE = _descriptor.EnumDescriptor(
  name='Roi3DMapType',
  full_name='autodrive.workflow.proto.Roi3DMapType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kRoi3DMapTypePtUndistortMap', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kRoi3DMapTypePtDistortMap', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kRoi3DMapTypeEqflUMap', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kRoi3DMapTypeEqflVMap', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=765,
  serialized_end=897,
)
_sym_db.RegisterEnumDescriptor(_ROI3DMAPTYPE)

Roi3DMapType = enum_type_wrapper.EnumTypeWrapper(_ROI3DMAPTYPE)
kReal3DTypePedestrian = 0
kReal3DTypeVehicle = 1
kReal3DTypeCyclist = 2
kRoi3DMapTypePtUndistortMap = 0
kRoi3DMapTypePtDistortMap = 1
kRoi3DMapTypeEqflUMap = 2
kRoi3DMapTypeEqflVMap = 3



_REAL3DRESULT = _descriptor.Descriptor(
  name='Real3DResult',
  full_name='autodrive.workflow.proto.Real3DResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bev_obstacle', full_name='autodrive.workflow.proto.Real3DResult.bev_obstacle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_3dbox', full_name='autodrive.workflow.proto.Real3DResult.img_3dbox', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_rect', full_name='autodrive.workflow.proto.Real3DResult.img_rect', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=303,
)


_REAL3DRESULTS = _descriptor.Descriptor(
  name='Real3DResults',
  full_name='autodrive.workflow.proto.Real3DResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='autodrive.workflow.proto.Real3DResults.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='autodrive.workflow.proto.Real3DResults.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinate_type', full_name='autodrive.workflow.proto.Real3DResults.coordinate_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real3d_result', full_name='autodrive.workflow.proto.Real3DResults.real3d_result', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=527,
)


_REAL3DDATA = _descriptor.Descriptor(
  name='Real3DData',
  full_name='autodrive.workflow.proto.Real3DData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='autodrive.workflow.proto.Real3DData.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real3d_results', full_name='autodrive.workflow.proto.Real3DData.real3d_results', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=673,
)

_REAL3DRESULT.fields_by_name['bev_obstacle'].message_type = dynamic__obstacle__pb2._DYNAMICOBSTACLE
_REAL3DRESULT.fields_by_name['img_3dbox'].message_type = perception__base__pb2._BOX3D
_REAL3DRESULT.fields_by_name['img_rect'].message_type = perception__base__pb2._RECT
_REAL3DRESULTS.fields_by_name['header'].message_type = perception__base__pb2._HEADER
_REAL3DRESULTS.fields_by_name['type'].enum_type = _REAL3DTYPE
_REAL3DRESULTS.fields_by_name['real3d_result'].message_type = _REAL3DRESULT
_REAL3DDATA.fields_by_name['header'].message_type = perception__base__pb2._HEADER
_REAL3DDATA.fields_by_name['real3d_results'].message_type = _REAL3DRESULTS
DESCRIPTOR.message_types_by_name['Real3DResult'] = _REAL3DRESULT
DESCRIPTOR.message_types_by_name['Real3DResults'] = _REAL3DRESULTS
DESCRIPTOR.message_types_by_name['Real3DData'] = _REAL3DDATA
DESCRIPTOR.enum_types_by_name['Real3DType'] = _REAL3DTYPE
DESCRIPTOR.enum_types_by_name['Roi3DMapType'] = _ROI3DMAPTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Real3DResult = _reflection.GeneratedProtocolMessageType('Real3DResult', (_message.Message,), dict(
  DESCRIPTOR = _REAL3DRESULT,
  __module__ = 'real3d_pb2'
  # @@protoc_insertion_point(class_scope:autodrive.workflow.proto.Real3DResult)
  ))
_sym_db.RegisterMessage(Real3DResult)

Real3DResults = _reflection.GeneratedProtocolMessageType('Real3DResults', (_message.Message,), dict(
  DESCRIPTOR = _REAL3DRESULTS,
  __module__ = 'real3d_pb2'
  # @@protoc_insertion_point(class_scope:autodrive.workflow.proto.Real3DResults)
  ))
_sym_db.RegisterMessage(Real3DResults)

Real3DData = _reflection.GeneratedProtocolMessageType('Real3DData', (_message.Message,), dict(
  DESCRIPTOR = _REAL3DDATA,
  __module__ = 'real3d_pb2'
  # @@protoc_insertion_point(class_scope:autodrive.workflow.proto.Real3DData)
  ))
_sym_db.RegisterMessage(Real3DData)


# @@protoc_insertion_point(module_scope)
