// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision_debug.proto

#ifndef PROTOBUF_vision_5fdebug_2eproto__INCLUDED
#define PROTOBUF_vision_5fdebug_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
#include "dynamic_obstacle_debug_info.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_vision_5fdebug_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsVisionDebugMsgImpl();
void InitDefaultsVisionDebugMsg();
inline void InitDefaults() {
  InitDefaultsVisionDebugMsg();
}
}  // namespace protobuf_vision_5fdebug_2eproto
namespace autodrive {
namespace workflow {
namespace proto {
class VisionDebugMsg;
class VisionDebugMsgDefaultTypeInternal;
extern VisionDebugMsgDefaultTypeInternal _VisionDebugMsg_default_instance_;
}  // namespace proto
}  // namespace workflow
}  // namespace autodrive
namespace autodrive {
namespace workflow {
namespace proto {

// ===================================================================

class VisionDebugMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:autodrive.workflow.proto.VisionDebugMsg) */ {
 public:
  VisionDebugMsg();
  virtual ~VisionDebugMsg();

  VisionDebugMsg(const VisionDebugMsg& from);

  inline VisionDebugMsg& operator=(const VisionDebugMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VisionDebugMsg(VisionDebugMsg&& from) noexcept
    : VisionDebugMsg() {
    *this = ::std::move(from);
  }

  inline VisionDebugMsg& operator=(VisionDebugMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VisionDebugMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VisionDebugMsg* internal_default_instance() {
    return reinterpret_cast<const VisionDebugMsg*>(
               &_VisionDebugMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(VisionDebugMsg* other);
  friend void swap(VisionDebugMsg& a, VisionDebugMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VisionDebugMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  VisionDebugMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const VisionDebugMsg& from);
  void MergeFrom(const VisionDebugMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(VisionDebugMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .autodrive.workflow.proto.DynamicObstacleDebugInfo obstacles_debug_info = 3;
  int obstacles_debug_info_size() const;
  void clear_obstacles_debug_info();
  static const int kObstaclesDebugInfoFieldNumber = 3;
  const ::autodrive::workflow::proto::DynamicObstacleDebugInfo& obstacles_debug_info(int index) const;
  ::autodrive::workflow::proto::DynamicObstacleDebugInfo* mutable_obstacles_debug_info(int index);
  ::autodrive::workflow::proto::DynamicObstacleDebugInfo* add_obstacles_debug_info();
  ::google::protobuf::RepeatedPtrField< ::autodrive::workflow::proto::DynamicObstacleDebugInfo >*
      mutable_obstacles_debug_info();
  const ::google::protobuf::RepeatedPtrField< ::autodrive::workflow::proto::DynamicObstacleDebugInfo >&
      obstacles_debug_info() const;

  // .autodrive.workflow.proto.MsgHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::autodrive::workflow::proto::MsgHeader& header() const;
  ::autodrive::workflow::proto::MsgHeader* release_header();
  ::autodrive::workflow::proto::MsgHeader* mutable_header();
  void set_allocated_header(::autodrive::workflow::proto::MsgHeader* header);

  // .autodrive.workflow.proto.Error error = 2;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::autodrive::workflow::proto::Error& error() const;
  ::autodrive::workflow::proto::Error* release_error();
  ::autodrive::workflow::proto::Error* mutable_error();
  void set_allocated_error(::autodrive::workflow::proto::Error* error);

  // @@protoc_insertion_point(class_scope:autodrive.workflow.proto.VisionDebugMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::autodrive::workflow::proto::DynamicObstacleDebugInfo > obstacles_debug_info_;
  ::autodrive::workflow::proto::MsgHeader* header_;
  ::autodrive::workflow::proto::Error* error_;
  mutable int _cached_size_;
  friend struct ::protobuf_vision_5fdebug_2eproto::TableStruct;
  friend void ::protobuf_vision_5fdebug_2eproto::InitDefaultsVisionDebugMsgImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VisionDebugMsg

// .autodrive.workflow.proto.MsgHeader header = 1;
inline bool VisionDebugMsg::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::autodrive::workflow::proto::MsgHeader& VisionDebugMsg::header() const {
  const ::autodrive::workflow::proto::MsgHeader* p = header_;
  // @@protoc_insertion_point(field_get:autodrive.workflow.proto.VisionDebugMsg.header)
  return p != NULL ? *p : *reinterpret_cast<const ::autodrive::workflow::proto::MsgHeader*>(
      &::autodrive::workflow::proto::_MsgHeader_default_instance_);
}
inline ::autodrive::workflow::proto::MsgHeader* VisionDebugMsg::release_header() {
  // @@protoc_insertion_point(field_release:autodrive.workflow.proto.VisionDebugMsg.header)
  
  ::autodrive::workflow::proto::MsgHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::autodrive::workflow::proto::MsgHeader* VisionDebugMsg::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::autodrive::workflow::proto::MsgHeader;
  }
  // @@protoc_insertion_point(field_mutable:autodrive.workflow.proto.VisionDebugMsg.header)
  return header_;
}
inline void VisionDebugMsg::set_allocated_header(::autodrive::workflow::proto::MsgHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:autodrive.workflow.proto.VisionDebugMsg.header)
}

// .autodrive.workflow.proto.Error error = 2;
inline bool VisionDebugMsg::has_error() const {
  return this != internal_default_instance() && error_ != NULL;
}
inline const ::autodrive::workflow::proto::Error& VisionDebugMsg::error() const {
  const ::autodrive::workflow::proto::Error* p = error_;
  // @@protoc_insertion_point(field_get:autodrive.workflow.proto.VisionDebugMsg.error)
  return p != NULL ? *p : *reinterpret_cast<const ::autodrive::workflow::proto::Error*>(
      &::autodrive::workflow::proto::_Error_default_instance_);
}
inline ::autodrive::workflow::proto::Error* VisionDebugMsg::release_error() {
  // @@protoc_insertion_point(field_release:autodrive.workflow.proto.VisionDebugMsg.error)
  
  ::autodrive::workflow::proto::Error* temp = error_;
  error_ = NULL;
  return temp;
}
inline ::autodrive::workflow::proto::Error* VisionDebugMsg::mutable_error() {
  
  if (error_ == NULL) {
    error_ = new ::autodrive::workflow::proto::Error;
  }
  // @@protoc_insertion_point(field_mutable:autodrive.workflow.proto.VisionDebugMsg.error)
  return error_;
}
inline void VisionDebugMsg::set_allocated_error(::autodrive::workflow::proto::Error* error) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(error_);
  }
  if (error) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      error = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:autodrive.workflow.proto.VisionDebugMsg.error)
}

// repeated .autodrive.workflow.proto.DynamicObstacleDebugInfo obstacles_debug_info = 3;
inline int VisionDebugMsg::obstacles_debug_info_size() const {
  return obstacles_debug_info_.size();
}
inline const ::autodrive::workflow::proto::DynamicObstacleDebugInfo& VisionDebugMsg::obstacles_debug_info(int index) const {
  // @@protoc_insertion_point(field_get:autodrive.workflow.proto.VisionDebugMsg.obstacles_debug_info)
  return obstacles_debug_info_.Get(index);
}
inline ::autodrive::workflow::proto::DynamicObstacleDebugInfo* VisionDebugMsg::mutable_obstacles_debug_info(int index) {
  // @@protoc_insertion_point(field_mutable:autodrive.workflow.proto.VisionDebugMsg.obstacles_debug_info)
  return obstacles_debug_info_.Mutable(index);
}
inline ::autodrive::workflow::proto::DynamicObstacleDebugInfo* VisionDebugMsg::add_obstacles_debug_info() {
  // @@protoc_insertion_point(field_add:autodrive.workflow.proto.VisionDebugMsg.obstacles_debug_info)
  return obstacles_debug_info_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::autodrive::workflow::proto::DynamicObstacleDebugInfo >*
VisionDebugMsg::mutable_obstacles_debug_info() {
  // @@protoc_insertion_point(field_mutable_list:autodrive.workflow.proto.VisionDebugMsg.obstacles_debug_info)
  return &obstacles_debug_info_;
}
inline const ::google::protobuf::RepeatedPtrField< ::autodrive::workflow::proto::DynamicObstacleDebugInfo >&
VisionDebugMsg::obstacles_debug_info() const {
  // @@protoc_insertion_point(field_list:autodrive.workflow.proto.VisionDebugMsg.obstacles_debug_info)
  return obstacles_debug_info_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace workflow
}  // namespace autodrive

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vision_5fdebug_2eproto__INCLUDED
