//
#ifndef AUTODRIVE_VERSION_H_
#define AUTODRIVE_VERSION_H_

#define HYPERSAR_VERSION_MAJOR 1
#define HYPERSAR_VERSION_MINOR 0
#define HYPERSAR_VERSION_PATCH 0

#define HYPERSAR_SONAME_VERSION_MAJOR 1
#define HYPERSAR_SONAME_VERSION_MINOR 31
#define HYPERSAR_SONAME_VERSION_PATCH 6

#endif
